### ISSUE TITLE
TODO MAP

### ISSUE THREAD

**Issue by Dias1c** [Dias1c/casbin-js#1]
- [x] Add links to ACL, RBAC, ABAC in README.md

**Comment by Dias1c** [comment]
- [ ] On reset callbacks (add, remove)
- [x] on ini callbacks (add, remove)

**Comment by Dias1c** [comment]
- [ ] switch to casbin instead of using casbin-core

**Comment by Dias1c** [comment]
- [ ] [readme] installation
- [x] [readme] changelogs
